### PR TITLE
full lifecycle for worker domains

### LINKED ISSUE #7: Persisting domains after `Pool.shutdown pool`
# Descrition of the issue

I'm toying with `moonpool` to parallelize some sampling library. In one of my tests, after I finish performing the compute-intensive work I perform a call to `Unix.fork` which fails with the following error:

```
raised exception `Failure("Unix.fork may not be called while other domains were created")`
on `()`
Raised by primitive operation at Unix in file "unix.ml" (inlined), line 213, characters 0-46
Called from Plot.GP_run.run_script.(fun) in file "gnuplot/src/plot.ml", line 1100, characters 10-22
Called from Dagger_tests__Poly.run in file "dagger/test/poly.ml", line 167, characters 2-29
Called from Dagger_tests__Poly.tests.(fun) in file "dagger/test/poly.ml", line 172, characters 6-12
Called from QCheck2.Test.run_law.loop in file "src/core/QCheck2.ml", line 1644, characters 27-32
Called from QCheck2.Test.run_law in file "src/core/QCheck2.ml", line 1649, characters 6-18
Called from QCheck2.Test.check_state_input in file "src/core/QCheck2.ml", line 1772, characters 2
```

My interpretation is that despite having performed a call to `Pool.shutdown`, the domains created by `moonpool` persist. I grepped the moonpool sources and I didn't see a `Domain.join`. I may totally be wrong though: the error message could be understood as "creating domains prevents forever to fork your process, even after the extra domains complete".

# Steps to reproduce

- clone the branch `dagger-moonpool-issue` on `https://gitlab.com/igarnier/monorepo`
- `cd dagger`
- `dune build @runtest`

The failing test is `dagger/test/poly.ml`, the call to `Unix.fork` is hidden in `gnuplot/src/plot.ml`

### PR DESCRIPTION
**Pull request by c-cube**
domains can now stop when all worker threads running on them are done

close #7

### CODE REVIEW

**Comment by c-cube** [comment]
it seems like domains and threads exit properly after the pool is shut down, but I still can't call `Unix.fork` after that. Maybe the runtime is conservative and assumes that once domains have been started it's too late?

**Comment by c-cube** [comment]
@igarnier could you try this please?

**Comment by igarnier** [comment]
> it seems like domains and threads exit properly after the pool is shut down, but I still can't call `Unix.fork` after that. Maybe the runtime is conservative and assumes that once domains have been started it's too late?

Yes, this is exactly the case. Once an extra domain is created, `Unix.fork` is out of the window. I ended up rewriting my program with one of the `create_process` functions, which are still usable.

**Comment by c-cube** [comment]
Thank you for testing :slightly_smiling_face: . This is still a useful PR in terms of resource consumptions, so I'll merge. Cheers!

**Pull request merged**
